### ISSUE TITLE
Get videos.csv

### ISSUE THREAD

**Issue by rjt31** [smg134/StreamVideo#4]
We need to make sure Dr. Collard (mlcollard), and the TA (pt33) are invited to be collaborators and then do a % git pull once Dr. Collard has put it into our master branch.

**Comment by rkg18** [comment]
@smg134 Could you add Dr. Collard and the TA to the repo since you have admin privileges when you have the chance so we can get the .csv?

**Comment by smg134** [comment]
I sent them invites about a week ago when I opened the repository. I'll email them the invite links directly because they must have missed it for some reason.

**Comment by rkg18** [comment]
Videos.csv added
