### ISSUE TITLE
Refactoring needed for Account class

### ISSUE THREAD

**Issue by rkg18** [smg134/StreamVideo#6]
The two main functions that need a rework are mainly report() and data(). 

I'll starting working on report()

**Comment by rkg18** [comment]
There are a couple a places where the code is similar like in the streamCount and in totalMinutes/totalHours. Since they're repeated we're allowed to create methods as long as they're for refactoring right and not additional functionality?

**Comment by smg134** [comment]
Yes you can add anything you need for refactoring.

**Comment by smg134** [comment]
I did some refactoring with how streamCount is calculated in both report() and data(). I'm going to let it sit for now so you all can get something done. I'll look at it again late tonight and work on whatever is left, if anything.

**Comment by rjt31** [comment]
I replaced some switch statements with if statements and moved v_type to the top so that it could be accessed everywhere and not have to be initialized twice.
